/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softmakerjava;

import java.awt.Color;
import java.awt.Component;
import java.awt.Event;
import java.awt.Label;
import java.awt.event.MouseEvent;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import oracle.jrockit.jfr.JFR;

/**
 *
 * @author Baka
 */
public class MainFrame extends javax.swing.JFrame
{
    
    public MainFrame(User user)
    {
        GeneralSettingsEditor.currentUser = user;
        initComponents();
        ownInit();
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
        }
        catch (ClassNotFoundException exc)
        {
            System.err.println("Error to load driver class - " + exc.getLocalizedMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JLabel();
        MenuPanel = new javax.swing.JPanel();
        codeEditorLabel = new javax.swing.JLabel();
        settingsPanelLabel = new javax.swing.JLabel();
        serverAcessPanel = new javax.swing.JLabel();
        taskPanel = new javax.swing.JLabel();
        employePanel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HeaderPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usernameLabel.setText("Welcome, PH");
        HeaderPanel.add(usernameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, 50));

        MenuPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        MenuPanel.setForeground(new java.awt.Color(153, 153, 153));
        MenuPanel.setLayout(new java.awt.GridLayout(3, 3));

        codeEditorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        codeEditorLabel.setText("Code editor");
        codeEditorLabel.setToolTipText("");
        MenuPanel.add(codeEditorLabel);

        settingsPanelLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        settingsPanelLabel.setText("Settings panel");
        MenuPanel.add(settingsPanelLabel);

        serverAcessPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serverAcessPanel.setText("Server access panel");
        MenuPanel.add(serverAcessPanel);

        taskPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskPanel.setText("Task panel");
        MenuPanel.add(taskPanel);

        employePanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        employePanel.setText("Employe panel");
        MenuPanel.add(employePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(HeaderPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(HeaderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 561, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ownInit()
    {
        final JFrame selfRef = this;
        for (Component comp : MenuPanel.getComponents())
        {
            JLabel tmpLabel = (JLabel) comp;
            tmpLabel.setBorder(BorderFactory.createLineBorder(Color.white, 2, false));
            tmpLabel.addMouseListener(new java.awt.event.MouseAdapter()
        {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                JLabel labelContent = (JLabel) evt.getComponent();
                
                switch(labelContent.getText())
                {
                    case "Code editor" :
                    {
                        CodeViewer codeView = new CodeViewer(selfRef);
                        selfRef.setVisible(false);
                        codeView.setVisible(true);
                        break;
                    }
                    case "Settings panel" :
                    {
                        SettingsPanel settingsView = new SettingsPanel(selfRef);
                        selfRef.setVisible(false);
                        settingsView.setVisible(true);
                        break;
                    }
                    case "Server access panel" :
                    {
                        ServerAcessWindow serverWindow = new ServerAcessWindow(selfRef);
                        selfRef.setVisible(false);
                        serverWindow.setVisible(true);
                        break;
                    }
                    case "Task panel" :
                    {
                        if (GeneralSettingsEditor.currentUser.getPosition().equals("manager"))
                        {
                            Vector<Task> V = new Vector<>(0);
                            TaskMenager TK = new TaskMenager();
                            V = TK.GenerateTaskList();
                            TaskPanel tp = new TaskPanel(V);
                        }
                        else
                            JOptionPane.showMessageDialog(selfRef, "Not available for your account!");
                        break;
                    }
                    case "Employe panel" :
                    {
                        if (GeneralSettingsEditor.currentUser.getPosition().equals("user"))
                        {
                            Vector<Task> V = new Vector<>(0);
                            TaskMenager TK = new TaskMenager();
                            V = TK.GenerateTaskList();
                            System.out.println(V.get(0).getName());
                            EmployeePanel ep = new EmployeePanel(V, GeneralSettingsEditor.currentUser);
                        }
                        else
                            JOptionPane.showMessageDialog(selfRef, "Not available for your account!");
                    }
                    default : System.out.println("Clicked : " + labelContent.getText());
                }
            }
        });
        }
        usernameLabel.setText("Welcome, " + GeneralSettingsEditor.currentUser.getName());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JLabel codeEditorLabel;
    private javax.swing.JLabel employePanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel serverAcessPanel;
    private javax.swing.JLabel settingsPanelLabel;
    private javax.swing.JLabel taskPanel;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
